version: 0.0
os: linux
#Resources:
#  - TargetService:
#      Type: AWS::ECS::Service
#      Properties:
#        TaskDefinition: "arn:aws:iam::659633980646:role/EC2ForCodeDeploy"
#        LoadBalancerInfo:
#          ContainerName: "SampleApplicationName"
#          ContainerPort: 80

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: server_clear.sh
      timeout: 20
      runas: ec2-user
  AfterInstall:
    - location: server_clear.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: server_stop.sh
      timeout: 60
      runas: ec2-user



#
#Hooks:
#  - BeforeInstall: "LambdaFunctionToValidateBeforeInstall"
#  - AfterInstall: "LambdaFunctionToValidateAfterInstall"
#  - AfterAllowTestTraffic: "LambdaFunctionToValidateAfterTestTrafficStarts"
#  - BeforeAllowTraffic: "LambdaFunctionToValidateBeforeAllowingProductionTraffic"
#  - AfterAllowTraffic: "LambdaFunctionToValidateAfterAllowingProductionTraffic"