version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    # steps:
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
#      - ./gradlew bootJar
      - gradle build
      # steps:
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
    - server_start.sh
#  name: TravelChat
  discard-paths:  yes
