version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    # steps:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew bootJar
      # steps:
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appspec.yml
#  name: TravelChat
  discard-paths:  yes
